import type {
  DataViewColumnPolicy,
  DataViewEditability,
  DataViewEditableTable,
  DataViewValueEditor,
} from "./dataView.js";

/** The projection facts PostgreSQL reports for one result column (RowDescription). */
export interface ProjectedField {
  name: string;
  tableID: number;
  columnID: number;
  dataTypeID: number;
}

export interface CatalogColumn {
  attnum: number;
  name: string;
  type: string;
  identity: "" | "a" | "d";
  generated: "" | "s" | "v";
  notNull: boolean;
  /** A DEFAULT, a sequence, an identity: PostgreSQL has a value even when nobody gives one. */
  hasDefault: boolean;
}

/**
 * Whether a new row cannot be written without a value for this column. Generated columns and
 * anything PostgreSQL fills in on its own are not demanded of the reader.
 */
export function columnDemandsValue(column: CatalogColumn): boolean {
  return column.notNull && !column.hasDefault && column.generated === "" && column.identity === "";
}

export interface CatalogUniqueIndex {
  attnums: number[];
  primary: boolean;
}

/** What PostgreSQL does to the rows that point at a row being deleted. */
export type DataViewDeleteRule = "no-action" | "restrict" | "cascade" | "set-null" | "set-default";

export interface CatalogTable {
  tableOid: number;
  schema: string;
  name: string;
  relkind: string;
  /** PostgreSQL may read descendant rows whose keys are not covered by this table's constraints. */
  hasSubclasses: boolean;
  columns: CatalogColumn[];
  uniqueIndexes: CatalogUniqueIndex[];
  foreignKeyAttnums: number[];
  /** Tables whose foreign keys point at this one, and what PostgreSQL does when a row goes. */
  referencedBy: { table: string; onDelete: DataViewDeleteRule }[];
}

export const READ_ONLY_REASONS = {
  computed: "Computed value: it does not come from one stored column.",
  ambiguous: "Ambiguous: this table appears more than once in the query.",
  notTable: "Only table rows can be edited here.",
  noIdentity: "Row identity is not projected: include the primary key columns to edit.",
  identity: "Identity value (primary key).",
  relationship: "Relationship value: it holds this row to the relation the query joined.",
  generatedIdentity: "Identity generated by PostgreSQL.",
  generated: "Generated column.",
  binary: "Binary values are read-only.",
  unknownColumn: "Column no longer exists in the catalog.",
  applying: "Changes are being applied.",
} as const;

/**
 * The type without what does not change what it is: `numeric(8,2)` is a numeric, `text[]` is a
 * text. Everything that classifies a column asks this first, so they all agree on the spelling —
 * the one the catalogue declares, `bigint` and `boolean`, not the internal `int8` and `bool`.
 */
export function baseTypeName(dataType: string): string {
  return dataType
    .replace(/\(.*\)/u, "")
    .replace(/\[\]$/u, "")
    .trim()
    .toLowerCase();
}

export function valueEditorForType(dataType: string): DataViewValueEditor {
  const base = baseTypeName(dataType);
  if (dataType.endsWith("[]")) return "text";
  switch (base) {
    case "boolean":
      return "boolean";
    case "smallint":
    case "integer":
    case "bigint":
    case "numeric":
    case "real":
    case "double precision":
      return "number";
    case "json":
    case "jsonb":
      return "json";
    case "date":
      return "date";
    case "time without time zone":
    case "time with time zone":
      return "time";
    case "timestamp without time zone":
    case "timestamp with time zone":
      return "timestamp";
    default:
      return "text";
  }
}

/**
 * Decides which projected columns can be edited. A stored row is identified when every column
 * of its primary key (or of a NOT NULL unique index) is projected exactly once.
 */
export function resolveDataViewEditability(
  fields: readonly ProjectedField[],
  catalog: readonly CatalogTable[],
): DataViewEditability {
  const columns: DataViewColumnPolicy[] = fields.map(() => ({
    editable: false,
    reason: READ_ONLY_REASONS.computed,
  }));
  const tables: DataViewEditableTable[] = [];
  // Ordinals a new row cannot go without: revealed the moment a reader adds one.
  const required: number[] = [];
  // Ordinals that identify a row or tie it to another relation: hidden by default.
  const technical: number[] = [];
  const byTable = new Map<number, number[]>();
  fields.forEach((field, ordinal) => {
    if (field.tableID > 0 && field.columnID > 0) {
      byTable.set(field.tableID, [...(byTable.get(field.tableID) ?? []), ordinal]);
    }
  });

  for (const [tableOid, ordinals] of byTable) {
    const table = catalog.find((candidate) => candidate.tableOid === tableOid);
    const markAll = (reason: string) => {
      for (const ordinal of ordinals) columns[ordinal] = { editable: false, reason };
    };
    if (!table) {
      markAll(READ_ONLY_REASONS.unknownColumn);
      continue;
    }
    if (table.relkind !== "r" && table.relkind !== "p") {
      markAll(READ_ONLY_REASONS.notTable);
      continue;
    }
    const seen = new Set<number>();
    const ambiguous = ordinals.some((ordinal) => {
      const attnum = fields[ordinal]?.columnID ?? 0;
      if (seen.has(attnum)) return true;
      seen.add(attnum);
      return false;
    });
    if (ambiguous) {
      markAll(READ_ONLY_REASONS.ambiguous);
      continue;
    }
    const ordinalByAttnum = new Map(
      ordinals.map((ordinal) => [fields[ordinal]?.columnID ?? 0, ordinal] as const),
    );
    const key = identifyingIndex(table, ordinalByAttnum);
    if (!key) {
      markAll(READ_ONLY_REASONS.noIdentity);
      continue;
    }
    const keyOrdinals = key.attnums.map((attnum) => ordinalByAttnum.get(attnum) ?? -1);
    const keyColumns = key.attnums.map(
      (attnum) => table.columns.find((column) => column.attnum === attnum)?.name ?? "",
    );
    const keyTypes = key.attnums.map(
      (attnum) => table.columns.find((column) => column.attnum === attnum)?.type ?? "text",
    );
    tables.push({
      tableOid,
      schema: table.schema,
      name: table.name,
      keyOrdinals,
      keyColumns,
      keyTypes,
      referencedBy: table.referencedBy,
    });
    for (const ordinal of ordinals) {
      const attnum = fields[ordinal]?.columnID ?? 0;
      const column = table.columns.find((candidate) => candidate.attnum === attnum);
      columns[ordinal] = columnPolicy(
        tableOid,
        column,
        key,
        table.foreignKeyAttnums,
        byTable.size > 1,
      );
      if (column && columnDemandsValue(column)) required.push(ordinal);
      if (
        column &&
        (key.attnums.includes(column.attnum) || table.foreignKeyAttnums.includes(column.attnum))
      )
        technical.push(ordinal);
    }
  }
  return { tables, columns, requiredOrdinals: required, technicalOrdinals: technical };
}

function identifyingIndex(
  table: CatalogTable,
  ordinalByAttnum: ReadonlyMap<number, number>,
): CatalogUniqueIndex | undefined {
  const usable = table.uniqueIndexes.filter((index) => {
    if (index.attnums.length === 0) return false;
    if (!index.attnums.every((attnum) => ordinalByAttnum.has(attnum))) return false;
    if (index.primary) return true;
    return index.attnums.every(
      (attnum) => table.columns.find((column) => column.attnum === attnum)?.notNull === true,
    );
  });
  return usable.find((index) => index.primary) ?? usable[0];
}

/**
 * `joined` says the projection comes from more than one relation. A relationship value is then
 * what holds the query together: changing it would silently move the row to another parent, under
 * a query composed for the one it had. Over a single table there is no join to protect, and the
 * column is one like any other — PostgreSQL still refuses a value that points at nothing.
 */
function columnPolicy(
  tableOid: number,
  column: CatalogColumn | undefined,
  key: CatalogUniqueIndex,
  foreignKeyAttnums: readonly number[],
  joined: boolean,
): DataViewColumnPolicy {
  if (!column) return { editable: false, reason: READ_ONLY_REASONS.unknownColumn };
  if (key.attnums.includes(column.attnum)) {
    return { editable: false, reason: READ_ONLY_REASONS.identity };
  }
  if (joined && foreignKeyAttnums.includes(column.attnum)) {
    return { editable: false, reason: READ_ONLY_REASONS.relationship };
  }
  if (column.identity === "a") {
    return { editable: false, reason: READ_ONLY_REASONS.generatedIdentity };
  }
  if (column.generated !== "") return { editable: false, reason: READ_ONLY_REASONS.generated };
  if (column.type === "bytea") return { editable: false, reason: READ_ONLY_REASONS.binary };
  return {
    editable: true,
    tableOid,
    column: column.name,
    dataType: column.type,
    editor: valueEditorForType(column.type),
    hasDefault: column.hasDefault || column.identity !== "" || column.generated !== "",
  };
}
