import type {
  DataViewColumnPolicy,
  DataViewEditability,
  DataViewEditableTable,
  DataViewValueEditor,
} from "./dataView.js";

/** The projection facts PostgreSQL reports for one result column (RowDescription). */
export interface ProjectedField {
  name: string;
  tableID: number;
  columnID: number;
  dataTypeID: number;
}

export interface CatalogColumn {
  attnum: number;
  name: string;
  type: string;
  identity: "" | "a" | "d";
  generated: "" | "s" | "v";
  notNull: boolean;
}

export interface CatalogUniqueIndex {
  attnums: number[];
  primary: boolean;
}

export interface CatalogTable {
  tableOid: number;
  schema: string;
  name: string;
  relkind: string;
  columns: CatalogColumn[];
  uniqueIndexes: CatalogUniqueIndex[];
  foreignKeyAttnums: number[];
}

export const READ_ONLY_REASONS = {
  computed: "Computed value: it does not come from one stored column.",
  ambiguous: "Ambiguous: this table appears more than once in the query.",
  notTable: "Only table rows can be edited here.",
  noIdentity: "Row identity is not projected: include the primary key columns to edit.",
  identity: "Identity value (primary key).",
  relationship: "Relationship value (foreign key).",
  generatedIdentity: "Identity generated by PostgreSQL.",
  generated: "Generated column.",
  binary: "Binary values are read-only.",
  unknownColumn: "Column no longer exists in the catalog.",
  applying: "Changes are being applied.",
} as const;

export function valueEditorForType(dataType: string): DataViewValueEditor {
  const base = dataType
    .replace(/\(.*\)/u, "")
    .replace(/\[\]$/u, "")
    .trim()
    .toLowerCase();
  if (dataType.endsWith("[]")) return "text";
  switch (base) {
    case "boolean":
      return "boolean";
    case "smallint":
    case "integer":
    case "bigint":
    case "numeric":
    case "real":
    case "double precision":
      return "number";
    case "json":
    case "jsonb":
      return "json";
    case "date":
      return "date";
    case "time without time zone":
    case "time with time zone":
      return "time";
    case "timestamp without time zone":
    case "timestamp with time zone":
      return "timestamp";
    default:
      return "text";
  }
}

/**
 * Decides which projected columns can be edited. A stored row is identified when every column
 * of its primary key (or of a NOT NULL unique index) is projected exactly once.
 */
export function resolveDataViewEditability(
  fields: readonly ProjectedField[],
  catalog: readonly CatalogTable[],
): DataViewEditability {
  const columns: DataViewColumnPolicy[] = fields.map(() => ({
    editable: false,
    reason: READ_ONLY_REASONS.computed,
  }));
  const tables: DataViewEditableTable[] = [];
  const byTable = new Map<number, number[]>();
  fields.forEach((field, ordinal) => {
    if (field.tableID > 0 && field.columnID > 0) {
      byTable.set(field.tableID, [...(byTable.get(field.tableID) ?? []), ordinal]);
    }
  });

  for (const [tableOid, ordinals] of byTable) {
    const table = catalog.find((candidate) => candidate.tableOid === tableOid);
    const markAll = (reason: string) => {
      for (const ordinal of ordinals) columns[ordinal] = { editable: false, reason };
    };
    if (!table) {
      markAll(READ_ONLY_REASONS.unknownColumn);
      continue;
    }
    if (table.relkind !== "r" && table.relkind !== "p") {
      markAll(READ_ONLY_REASONS.notTable);
      continue;
    }
    const seen = new Set<number>();
    const ambiguous = ordinals.some((ordinal) => {
      const attnum = fields[ordinal]?.columnID ?? 0;
      if (seen.has(attnum)) return true;
      seen.add(attnum);
      return false;
    });
    if (ambiguous) {
      markAll(READ_ONLY_REASONS.ambiguous);
      continue;
    }
    const ordinalByAttnum = new Map(
      ordinals.map((ordinal) => [fields[ordinal]?.columnID ?? 0, ordinal] as const),
    );
    const key = identifyingIndex(table, ordinalByAttnum);
    if (!key) {
      markAll(READ_ONLY_REASONS.noIdentity);
      continue;
    }
    const keyOrdinals = key.attnums.map((attnum) => ordinalByAttnum.get(attnum) ?? -1);
    const keyColumns = key.attnums.map(
      (attnum) => table.columns.find((column) => column.attnum === attnum)?.name ?? "",
    );
    const keyTypes = key.attnums.map(
      (attnum) => table.columns.find((column) => column.attnum === attnum)?.type ?? "text",
    );
    tables.push({
      tableOid,
      schema: table.schema,
      name: table.name,
      keyOrdinals,
      keyColumns,
      keyTypes,
    });
    for (const ordinal of ordinals) {
      const attnum = fields[ordinal]?.columnID ?? 0;
      const column = table.columns.find((candidate) => candidate.attnum === attnum);
      columns[ordinal] = columnPolicy(tableOid, column, key, table.foreignKeyAttnums);
    }
  }
  return { tables, columns };
}

function identifyingIndex(
  table: CatalogTable,
  ordinalByAttnum: ReadonlyMap<number, number>,
): CatalogUniqueIndex | undefined {
  const usable = table.uniqueIndexes.filter((index) => {
    if (index.attnums.length === 0) return false;
    if (!index.attnums.every((attnum) => ordinalByAttnum.has(attnum))) return false;
    if (index.primary) return true;
    return index.attnums.every(
      (attnum) => table.columns.find((column) => column.attnum === attnum)?.notNull === true,
    );
  });
  return usable.find((index) => index.primary) ?? usable[0];
}

function columnPolicy(
  tableOid: number,
  column: CatalogColumn | undefined,
  key: CatalogUniqueIndex,
  foreignKeyAttnums: readonly number[],
): DataViewColumnPolicy {
  if (!column) return { editable: false, reason: READ_ONLY_REASONS.unknownColumn };
  if (key.attnums.includes(column.attnum)) {
    return { editable: false, reason: READ_ONLY_REASONS.identity };
  }
  if (foreignKeyAttnums.includes(column.attnum)) {
    return { editable: false, reason: READ_ONLY_REASONS.relationship };
  }
  if (column.identity === "a") {
    return { editable: false, reason: READ_ONLY_REASONS.generatedIdentity };
  }
  if (column.generated !== "") return { editable: false, reason: READ_ONLY_REASONS.generated };
  if (column.type === "bytea") return { editable: false, reason: READ_ONLY_REASONS.binary };
  return {
    editable: true,
    tableOid,
    column: column.name,
    dataType: column.type,
    editor: valueEditorForType(column.type),
  };
}
